name: elearning
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.2
  animations: ^2.0.3
  curved_navigation_bar: ^1.0.3
  percent_indicator: ^4.2.3
  cloud_firestore: ^4.8.0
  firebase_database: ^10.2.2
  firebase_storage: ^11.2.2
  file_picker: ^5.3.2
  flutter_pdfview: ^1.3.1
  floating_bottom_navigation_bar: ^1.5.2
  image_picker: ^0.8.7+5
  intl: ^0.18.1
  shared_preferences: ^2.1.2
  cupertino_icons: ^1.0.2
  flutter_datetime_picker: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/intro/
    - assets/intro/d3/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/POPPINS-REGULAR.TTF
        - asset: assets/fonts/POPPINS-MEDIUM.ttf
          weight: 500
        - asset: assets/fonts/POPPINS-SEMIBOLD.ttf
          weight: 600
        - asset: assets/fonts/POPPINS-BOLD.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 400
