// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIIzTlrYbPQKeuhygzvNIQTHzuHiWsq6g',
    appId: '1:542508031244:web:03e7e042b1bf081edbbd29',
    messagingSenderId: '542508031244',
    projectId: 'elearning-24eb0',
    authDomain: 'elearning-24eb0.firebaseapp.com',
    storageBucket: 'elearning-24eb0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYtotGGFp0h0PrMnHsAWXrOO2D1VqlTiI',
    appId: '1:542508031244:android:a0a351fc7b50e83bdbbd29',
    messagingSenderId: '542508031244',
    projectId: 'elearning-24eb0',
    storageBucket: 'elearning-24eb0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtOFR1cny2Yp_7y7ieBypbunnP2q1zlHs',
    appId: '1:542508031244:ios:98ee2969b937d23fdbbd29',
    messagingSenderId: '542508031244',
    projectId: 'elearning-24eb0',
    storageBucket: 'elearning-24eb0.appspot.com',
    iosClientId:
        '542508031244-paa7gbp702hvbkelttkkjpnfmbtko0d6.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );
}
